### ISSUE TITLE
badge: Turkish for ramazaneris

### ISSUE THREAD

**Issue by ramazaneris** [revoltchat/translations#104]
### What language(s) did you translate?

Turkish

### What is your Revolt ID?

01FCXFBQPYCBZWX40NSBYXYAWW

### Link to Weblate profile

https://weblate.insrt.uk/user/Jeosty/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @kerizalperwastaken

**Comment by ramazaneris** [comment]
I'm still waiting

**Comment by Rexogamer** [comment]
Duplicate of #159.
