### ISSUE TITLE
badge: Hindi for Yeikzy

### ISSUE THREAD

**Issue by Yeikzy** [revoltchat/translations#105]
### What language(s) did you translate?

French, German

### What is your Revolt ID?

01FFHHBTT8RA8PFE8SY9112AA8

### Link to Weblate profile

https://weblate.insrt.uk/user/Yeikzy/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Hades785** [comment]
Hey, I'm the maintainer for the French localisation of Revolt. I just have a few remarks and questions.
All your contributions are from around ten months ago, so I imagine you had the translator badge before and are looking to get it back after the change in how it's managed?

You have six contributions to the French _glossary_ on Weblate (one addition, two edits, and three suggestions accepted, one of which on your addition), none on the actual web app localisation, so there is not a lot to judge your translation ability by.

But something leaves me confused, and that is the rest of your activity history on Weblate:
- One addition to Serbian (web app)
- One addition to Catalan (glossary)
- Two additions to Korean (glossary)
- Three additions to Albanian (glossary), and one suggestion removed on one of your additions
- One addition to German (glossary), and one suggestion removed and added back as is, which is probably the result of clicking edit on it
- One addition to Bulgarian (glossary)
- Twenty-four additions (as well as sixteen more added but marked for editing) and two edits to Hindi (web app)

Was it to inflate your number of contributions over the fifty required to get the badge back then?
I'm just curious. It'd be cool if they were genuine contributions but I have my doubts on that.

Sadly, as things stand, I don't have much to go on to approve of your badge request _for the French language_. You'd have much more of a chance with the Hindi language with how many contributions you have on it, though that would require the approval of the maintainer for the Hindi localisation.

Have a good day,
Fuzuki.

**Comment by Yeikzy** [comment]
@Hades785 

> Hey, I'm the maintainer for the French localisation of Revolt. I just have a few remarks and questions. All your contributions are from around ten months ago, so I imagine you had the translator badge before and are looking to get it back after the change in how it's managed?
> 
> You have six contributions to the French _glossary_ on Weblate (one addition, two edits, and three suggestions accepted, one of which on your addition), none on the actual web app localisation, so there is not a lot to judge your translation ability by.
> 
> But something leaves me confused, and that is the rest of your activity history on Weblate:
> 
> * One addition to Serbian (web app)
> * One addition to Catalan (glossary)
> * Two additions to Korean (glossary)
> * Three additions to Albanian (glossary), and one suggestion removed on one of your additions
> * One addition to German (glossary), and one suggestion removed and added back as is, which is probably the result of clicking edit on it
> * One addition to Bulgarian (glossary)
> * Twenty-four additions (as well as sixteen more added but marked for editing) and two edits to Hindi (web app)
> 
> Was it to inflate your number of contributions over the fifty required to get the badge back then? I'm just curious. It'd be cool if they were genuine contributions but I have my doubts on that.
> 
> Sadly, as things stand, I don't have much to go on to approve of your badge request _for the French language_. You'd have much more of a chance with the Hindi language with how many contributions you have on it, though that would require the approval of the maintainer for the Hindi localisation.
> 
> Have a good day, Fuzuki.

Good evening,

To answer your message, I simply put French because it was my mother tongue. As for my contributions, I have contributed to a lot of languages on Revolt, hence my request for a badge.

Cordially, Good evening
Yeikzy.

**Comment by Rexogamer** [comment]
I'll cc @Infiniticity for the Hindi changes; I think given the situation here it's the best language to focus on

**Comment by Infiniticity** [comment]
Approved.

**Comment by Rexogamer** [comment]
Done in cfb1407a4ec0613b4394e20b6d1d859b61f64776
