### ISSUE TITLE
badge: Arabic for NoLogicAlan

### ISSUE THREAD

**Issue by NoLogicAlan** [revoltchat/translations#107]
### What language(s) did you translate?

Arabic

### What is your Revolt ID?

01FVB1ZGCPS8TJ4PD4P7NAFDZA

### Link to Weblate profile

https://weblate.insrt.uk/user/NoLogicAlan/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @LedaThemis

**Comment by LedaThemis** [comment]
Thanks for the mention!
From what I see you have 19 recent contributions from 4 months ago, and others 10-11 months ago.

Some notes:

You translated "Focus" as "ركز" which is a verb, even though in this context it's meant as "Focus state" (same with "Do not disturb").
Which I can understand if you haven't used the app much, however:

You translated "Search themes…" as "سمات البحث ...", even though in this context it's meant as "Search for themes..." not "Themes of search" (11 months ago, and edited it 4 months ago removing the space character).

And finally, "Seasonal Theme" as "موضوع موسمي", which is not consistent with the translation that you used for the word "theme" in the above (even though the edits were two minutes apart).

From the above, I can't approve your badge request for the Arabic language.

But I see that you have more contributions in Kurdish (Central), so you might want to apply for badge in that.

**Comment by NoLogicAlan** [comment]
before u be a Maintainers i have the badge and i translate more than u, and this 3 wrong spilling i can fixed anytime ;)

**Comment by janderedev** [comment]
> before u be a Maintainers i have the badge and i translate more than u, and this 3-or more idk 😄 wrong spilling i can fixed anytime ;) / i do that again because they take the badge from all.
> 

Obviously this decision is up to the language maintainer, but I would personally be hesitant with granting a translator badge here. Your reply is full of typos and makes zero sense grammatically, and I genuinely can't figure out what you're trying to say - Doesn't make a good impression to me considering the goal is to have accurate translations

**Comment by Rexogamer** [comment]
Your response to this kind of criticism isn't exactly encouraging. Kurdish isn't currently maintained - while you seem to have made plenty of contributions in Kurdish, this kind of attitude concerns me so I'm hesitant to offer you the role of maintainer.

**Comment by NoLogicAlan** [comment]
> > before u be a Maintainers i have the badge and i translate more than u, and this 3-or more idk 😄 wrong spilling i can fixed anytime ;) / i do that again because they take the badge from all.
> 
> Obviously this decision is up to the language maintainer, but I would personally be hesitant with granting a translator badge here. Your reply is full of typos and makes zero sense grammatically, and I genuinely can't figure out what you're trying to say - Doesn't make a good impression to me considering the goal is to have accurate translations

yeah u right sry

**Comment by NoLogicAlan** [comment]
> Your response to this kind of criticism isn't exactly encouraging. Kurdish isn't currently maintained - while you seem to have made plenty of contributions in Kurdish, this kind of attitude concerns me so I'm hesitant to offer you the role of maintainer.

oh okay but @fatalerrorcoded is a maintainer is normal add more than 1 maintainer ?

**Comment by Rexogamer** [comment]
Fatal isn't a maintainer for Kurdish..?

**Comment by NoLogicAlan** [comment]
> Fatal isn't a maintainer for Kurdish..?

oh yeah sry > @fanticwastaken

**Comment by Rexogamer** [comment]
Ahh; as for your original question, it isn't *unusual* for languages to have multiple maintainers but I'm still somewhat hesitant; I'll let Fantic weigh in in regards to giving you a badge for contributing to Kurdish though

**Comment by NoLogicAlan** [comment]
> Ahh; as for your original question, it isn't _unusual_ for languages to have multiple maintainers but I'm still somewhat hesitant; I'll let Fantic weigh in in regards to giving you a badge for contributing to Kurdish though

no no leave it, no need if i can be Contributors is okay for me

**Comment by Rexogamer** [comment]
...yes, I was saying "wait for them to check over your contributions"

**Comment by fanticwastaken** [comment]
@Rexogamer Alan has contributed for Central Kurdish

**Comment by NoLogicAlan** [comment]
🎊

**Comment by Rexogamer** [comment]
Done in 8ecd1a1
