### ISSUE TITLE
badge: Multiple languages for Neoselura

### ISSUE THREAD

**Issue by ghost** [revoltchat/translations#108]
### What language(s) did you translate?

Azerbaijani, Greek, French, Italian

### What is your Revolt ID?

01GQXMBTMMZHX5ARWCMJCVPX4Z

### Link to Weblate profile

https://weblate.insrt.uk/user/Neoselura/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @SingleSlice (for Italian), Hades785 (for French) and @janast3369 (for Greek)

**Comment by Rexogamer** [comment]
cc @SingleSlice (for Italian) and @Hades785 (for French)

**Comment by Rexogamer** [comment]
also @SudoJanast for Greek (they changed their username so I also need to update the maintainers data)

**Comment by Hades785** [comment]
The contributions to French are just the last three strings that were added yesterday.
And it feels kinda like machine translation tbh…
(I wanted to ask for context for those strings later but didn't get to it, imma do that right quick on Revolt)

I don't know about the other contributions.

**Comment by Neoselura** [comment]
Hello,
Turkish is my native language. I learned English in 6 months by taking a course on Udemy. I am still improving my English. I did my Italian and Greek translations with the help of my friend. I have an intermediate level of Latin and I have tried to use this knowledge in my Italian translations. I have been learning French for 2 months. I translated strings that seemed relatively simple to me. If there are any mistakes in the translations, I would be very grateful if you could tell me.
Regards,
Neoselura.

**Comment by SingleSlice** [comment]
![image](https://user-images.githubusercontent.com/32547537/215551415-1059b3e8-c533-4f93-be10-04c1f239eb63.png)
woop
