### ISSUE TITLE
badge: Indonesia for invalid

### ISSUE THREAD

**Issue by ilhamfauzan** [revoltchat/translations#111]
### What language(s) did you translate?

Indonesia

### What is your Revolt ID?

01FEKNC45SA690T7NE64V81XDZ

### Link to Weblate profile

https://weblate.insrt.uk/user/invalid/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @liimee

**Comment by liimee** [comment]
looks good

**Comment by Rexogamer** [comment]
Done in 4ade686
