### ISSUE TITLE
badge: Russian for PWGod

### ISSUE THREAD

**Issue by PWGod** [revoltchat/translations#114]
### What language(s) did you translate?

Russian, English

### What is your Revolt ID?

01GSX5DHKJYVG1ZW8EK9KKB8CZ

### Link to Weblate profile

https://weblate.insrt.uk/user/PWGood/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @div2005

**Comment by div2005** [comment]
@Rexogamer I don't see any activity on this account

**Comment by Rexogamer** [comment]
Based on the concerns of Div, I'm going to close this and #113 - feel free to open a new badge request if you contribute translations in the future ^^
