### ISSUE TITLE
badge: malay for ZEP1982

### ISSUE THREAD

**Issue by ZEP1982** [revoltchat/translations#115]
### What language(s) did you translate?

Malay

### What is your Revolt ID?

01GV2AANMPCSH2S4DDZHYJEK00

### Link to Weblate profile

https://weblate.insrt.uk/user/ZEP1982/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by ZEP1982** [comment]
Oh srry its ms

**Comment by Rexogamer** [comment]
Yes, but it doesn't appear to have a maintainer

**Comment by ZEP1982** [comment]
Lemme send u the maintainer
https://github.com/revoltchat/translations/blob/master/ms.json

**Comment by Rexogamer** [comment]
![Screenshot_20230309-184405.png](https://user-images.githubusercontent.com/42586271/224124416-9ab24d70-9883-4ad2-acfc-3020de7a40ca.png)

**Comment by ZEP1982** [comment]
Oh wait im dum 🤦
