### ISSUE TITLE
badge: Hindi for FreakyMAN 

### ISSUE THREAD

**Issue by FakeFerg** [revoltchat/translations#117]
### What language(s) did you translate?

Hindi

### What is your Revolt ID?

01GV50FAT8HWAHG4SV43FEA3WF

### Link to Weblate profile

https://weblate.insrt.uk/user/FreakyMAN/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @Infiniticity

**Comment by FakeFerg** [comment]
cc @infinitycity

**Comment by Rexogamer** [comment]
Why did you ping them again

**Comment by Infiniticity** [comment]
Approved.

**Comment by Rexogamer** [comment]
Done in e0ab566
