### ISSUE TITLE
maintain: pl

### ISSUE THREAD

**Issue by HosachiPL** [revoltchat/translations#119]
### What language do you want to maintain?

pl

### Link to Weblate profile

https://weblate.insrt.uk/user/Hosek/

### Revolt ID

01GV8QBV3ZHSX00K20GVRVJESY

**Comment by Rexogamer** [comment]
cc @jacekpoz

**Comment by jacekpoz** [comment]
wait can a language have multiple maintainers or are you asking me to kick myself off

**Comment by HosachiPL** [comment]
I don't even know who you are, i just see some mistakes in the translations and want to fix it.
I don't want to get limited by the waiting time and some other limitations while not being a mainainer.
If you don't want to me to become a mainainer just say it, ill close the issue, ask for the translator badge and move on

**Comment by Rexogamer** [comment]
Languages can have multiple maintainers

**Comment by HosachiPL** [comment]
So...does that mean that i can become one? 
Also, will i get the translator badge on revolt when being an maintainer?

**Comment by Rexogamer** [comment]
As jacekpoz doesn't seem to have any issues with your translations, I'll add you in a bit

**Comment by Rexogamer** [comment]
Done in f9d6094
