### ISSUE TITLE
badge: Czech for The Canine

### ISSUE THREAD

**Issue by Cikarin3** [revoltchat/translations#120]
### What language(s) did you translate?

Czech

### What is your Revolt ID?

01FXJGC0S2YQHQVADT74568DQN

### Link to Weblate profile

https://weblate.insrt.uk/user/TheCanine/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Cikarin3** [comment]
More details already provided in the #Translators channel, but I was told I had to request that my badge be returned here.

**Comment by Rexogamer** [comment]
Approved by @fatalerrorcoded.

**Comment by Rexogamer** [comment]
Fixed in 6fd1006cc4e7811688c9b2f8313a4a833998f6fa
