### ISSUE TITLE
badge: German, Polish for @sword

### ISSUE THREAD

**Issue by arktn** [revoltchat/translations#121]
### What language(s) did you translate?

German, Polish

### What is your Revolt ID?

01FQT99TE7G09HEJZA3EBYV96S

### Link to Weblate profile

https://weblate.insrt.uk/user/fez/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @janderedev / @jacekpoz

**Comment by janderedev** [comment]
Looked over the German translations and while most of them were fine, a couple of them had obvious errors.

- "Default themes" => "Standard Themen" (Correct would be "Standardthemen")
- "User Management" => "Benutzer Verwaltung" (Same thing, "Benutzerverwaltung")
- "Manage saved" => "Verwaltung gesichert" (This looks either machine translated or translated by someone who doesn't know German very well, I think this string is currently unused but I am unable to come up with any context in which that would be remotely right. Correct would probably be "Gespeicherte [...] verwalten", depending on the context in which it is used)

**Comment by arktn** [comment]
@janderedev I speak German fluently, it's my first language. Looking at the first two erros I don't know what I was thinking, but I can explain the third one. Since I couldn't find the text anywhere in the App I had to take a guess and I didn't look at it as "Manage saved **...** " but as a singular message that stated that for example a certain type of settings were saved. Looking back at it, it makes no sense but they are also like probably 1-2 years old and I didn't check over them again just wanted to get my badge back.

Proof of me actually being able to speak German: Hab jetzt nicht wirklich ne Ahnung was ich hier großes hinschreiben soll versuche einf n paar Abkürzungen einzubauen, dass man merkt ich hab den Mist nicht mitm Übersetzer geschrieben. Joa hoffe das reicht, denke mal du sprichst ja auch Deutsch also kannste das wohl selber n bissl einschätzen.
MfG :+1:

**Comment by jacekpoz** [comment]
in some places the translations are fine, but there's cases where you either ignore the context in which the string is used: 

`app.settings.pages.theme_shop.by` -> "za pomocą", where it refers to ownership, not to some tool / program used to make the theme

cases where your changes aren't consistent with the other translations:

`login.welcome2` -> "Witaj!", while `login.welcome` is "Witamy spowrotem!", so both should probably be plural

and cases where you're simply wrong or it just sounds weird (it's as shrimple as that):

`app.settings.pages.theme_shop.category.new` -> "Nowość w tym tygodniu" which should be plural
`app.settings.pages.bots.profile` -> "Bot profil" which sounds weird, the current one sounds better
`app.settings.pages.appearance.theme_options.seasonal_desc` -> "[...] w okresie sezony świąteczne." which uses "okresie" (singular) and then right after, referring to "sezony świąteczne" (plural)
`app.settings.pages.audio.button_grant` -> "Dać pozwolenie" which should be directed at the user
`app.home.feedback` -> "Przekaż opinię w Revolt" which translates to "Give feedback into Revolt"

... and so on, in some places ignoring how the others were written and not keeping the translations consistent or making mistakes

you shouldn't be a maintainer, it's better if someone checks your translations before they get approved

**Comment by jacekpoz** [comment]
btw hi jan :3

**Comment by jacekpoz** [comment]
> you shouldn't be a maintainer, it's better if someone checks your translations before they get approved

ok nvm I just went on autopilot and just realised this is a badge request and not about becoming a maintainer, but still some of them are really bad so IDK

**Comment by arktn** [comment]
@jacekpoz tak, moj polski nie jest taki dobri. Podstwy znam, bo mieszkam blisko granicy i przes dwa lata uczylam sie polskiego w szkle.

**Comment by arktn** [comment]
> in some places the translations are fine, but there's cases where you either ignore the context in which the string is used: 
> 
> 
> 
> `app.settings.pages.theme_shop.by` -> "za pomocą", where it refers to ownership, not to some tool / program used to make the theme
> 
> 
> 
> cases where your changes aren't consistent with the other translations:
> 
> 
> 
> `login.welcome2` -> "Witaj!", while `login.welcome` is "Witamy spowrotem!", so both should probably be plural
> 
> 
> 
> and cases where you're simply wrong or it just sounds weird (it's as shrimple as that):
> 
> 
> 
> `app.settings.pages.theme_shop.category.new` -> "Nowość w tym tygodniu" which should be plural
> 
> `app.settings.pages.bots.profile` -> "Bot profil" which sounds weird, the current one sounds better
> 
> `app.settings.pages.appearance.theme_options.seasonal_desc` -> "[...] w okresie sezony świąteczne." which uses "okresie" (singular) and then right after, referring to "sezony świąteczne" (plural)
> 
> `app.settings.pages.audio.button_grant` -> "Dać pozwolenie" which should be directed at the user
> 
> `app.home.feedback` -> "Przekaż opinię w Revolt" which translates to "Give feedback into Revolt"
> 
> 
> 
> ... and so on, in some places ignoring how the others were written and not keeping the translations consistent or making mistakes
> 
> 
> 
> you shouldn't be a maintainer, it's better if someone checks your translations before they get approved

I don't intend on adding more translations or becoming a maintainer to/for Polish. I controbuted to polish back when it was like 10 to 20% translated and there weren't many polish translators so I gve it my best shot.

**Comment by arktn** [comment]
@jacekpoz

**Comment by Rexogamer** [comment]
I'll mark this as approved for German but denied for Polish

**Comment by Rexogamer** [comment]
Done in cfb1407a4ec0613b4394e20b6d1d859b61f64776
