### ISSUE TITLE
badge: Arabic for Asl

### ISSUE THREAD

**Issue by Asl-script** [revoltchat/translations#126]
### What language(s) did you translate?

Arabic (Najdi)

### What is your Revolt ID?

01GVJWPZBN93MNSHBB96448D7W

### Link to Weblate profile

https://weblate.insrt.uk/user/Asl/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @LedaThemis

**Comment by LedaThemis** [comment]
Thanks for the mention!
From what I see, you have 8 recent contributions in Arabic (Najdi).

Some notes:

* You translated "Disabled" as "معاق" which means _disabled person_, even though in this context it's meant as "inactive".

* You translated "On" as "على" which is a preposition, even though in this context it's meant as "active/enabled".

* And finally, "Off" as "خارج" which means _outside_, even though in this context it's meant as "inactive/disabled".

As things stand, I regret to inform you that I cannot approve your badge request for the Arabic language.
