### ISSUE TITLE
badge: German for WaldperlachFabi

### ISSUE THREAD

**Issue by WaldperlachFabi** [revoltchat/translations#128]
### What language(s) did you translate?

German

### What is your Revolt ID?

01GVK1R9TWDZCD5B1R5FR89RQC

### Link to Weblate profile

https://weblate.insrt.uk/user/WaldperlachFabi/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @janderedev

**Comment by Rexogamer** [comment]
looks like she missed this; cc @sussycatgirl

**Comment by sussycatgirl** [comment]
You've made... 4 contributions, 2 of which are nonsense? You translated "On" to "Create an account" and "About" to "Log in".
