### ISSUE TITLE
maintain: Romanian

### ISSUE THREAD

**Issue by Edward205** [revoltchat/translations#131]
### What language do you want to maintain?

Romanian

### Link to Weblate profile

https://weblate.insrt.uk/user/Edward205/

### Revolt ID

01F82KZF9R7KF7JQJRTHGTQEEV

**Comment by Edward205** [comment]
Thanks. Am I going to be added to the list in the README?

**Comment by Rexogamer** [comment]
Done in f9d6094

**Comment by Edward205** [comment]
Okay. Thanks.
