### ISSUE TITLE
badge: Estonian for Asl

### ISSUE THREAD

**Issue by Asl-script** [revoltchat/translations#132]
### What language(s) did you translate?

Estonian

### What is your Revolt ID?

01GVJWPZBN93MNSHBB96448D7W

### Link to Weblate profile

https://weblate.insrt.uk/user/Asl/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @u032

**Comment by Asl-script** [comment]
> cc @u032

Correct me if im wrong but when I clicked their profile, they either changed their name or they deleted their account.

**Comment by Rexogamer** [comment]
Looks like they've changed their name; cc @orchst

**Comment by Rexogamer** [comment]
> > Looks like they've changed their name; cc @orchst
> 
> I just spoke to his friends on discord and they said he is basically inactive. I applied to be the new maintainer.

Would you mind sharing some kind of evidence?

**Comment by Asl-script** [comment]
![6A41DFB1-6240-4536-8F1A-F0C7FA093308](https://user-images.githubusercontent.com/35615903/225732148-cfbc45d9-03cc-406a-bc6b-a69cbb3934fe.png)
This is from the discord link on his website on his GitHub profile.

**Comment by Rexogamer** [comment]
Noted

**Comment by Rexogamer** [comment]
Done in 8310e82
