### ISSUE TITLE
maintain: dutch/nl

### ISSUE THREAD

**Issue by sympact06** [revoltchat/translations#134]
### What language do you want to maintain?

Dutch/NL

### Link to Weblate profile

https://weblate.insrt.uk/user/Sympact/

### Revolt ID

01FEVPQKFT45A9FCXM1YS4YMQG

**Comment by Rexogamer** [comment]
19 translations seems pretty low; your translations generally look fine but hmm

**Comment by sympact06** [comment]
There where no other translations that needs to be done. But I will keep it updated

**Comment by Rexogamer** [comment]
Done in f9d6094
