### ISSUE TITLE
maintain: Estonian

### ISSUE THREAD

**Issue by Asl-script** [revoltchat/translations#135]
### What language do you want to maintain?

Estonian

### Link to Weblate profile

https://weblate.insrt.uk/user/Asl/

### Revolt ID

01GVJWPZBN93MNSHBB96448D7W

**Comment by Asl-script** [comment]
Thank you vm for the opportunity, what is the next step from here?

**Comment by Rexogamer** [comment]
I will deal with every issue that has been labled as approved soon

**Comment by Asl-script** [comment]
> I will deal with every issue that has been labelled as approved soon

Thank you very much!

**Comment by Asl-script** [comment]
Please comment when you have given me perms to approve translations.

thanks,
Asl

**Comment by Rexogamer** [comment]
Done in 8310e82
