### ISSUE TITLE
badge: Arabic, arabic nadji for Darek0

### ISSUE THREAD

**Issue by DareksCoffee** [revoltchat/translations#138]
### What language(s) did you translate?

Arabic, Arabic najdi

### What is your Revolt ID?

01GVJSZRHBQZB2FFPCVJFPA8PP

### Link to Weblate profile

https://weblate.insrt.uk/user/Darek0/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @LedaThemis

**Comment by LedaThemis** [comment]
Thanks for the mention!

Hey Darek,
Upon reviewing your recent contributions in Arabic, I have a few notes to share with you.

Firstly, I noticed that you translated "Report server" as "تقرير الخادم", which means "server essay". However, in this context, it should be translated as "Report this server".

Secondly, the term "Reported" was translated as "ذكرت", which means "noted". This is inconsistent with the aforementioned correction and is incorrect.

Lastly, "block" was translated differently in two separate sentences where it should have been the same 
("هل ترغب في **منع** هذا المستخدم؟" and "لا **تحجب**").

Unfortunately, based on the issues stated above, I am unable to approve your badge request for the Arabic language.

Was that too formal? (My bad if it was!)

P.S. I don't think I should be maintaining Arabic (Najdi), as I don't have much knowledge about it. @Rexogamer (Should this be a separate issue?)

**Comment by Rexogamer** [comment]
You're currently only listed as a maintainer for regular Arabic; I think your response was fine btw
