### ISSUE TITLE
badge: <Latin> for <Rymko.>

### ISSUE THREAD

**Issue by rymko** [revoltchat/translations#144]
### What language(s) did you translate?

Latin

### What is your Revolt ID?

01GVT7QG1VMXK9C4NQZE9THHWX

### Link to Weblate profile

https://weblate.insrt.uk/user/Rymko/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
Closing n favour of #158.
