### ISSUE TITLE
badge: Armenians for Kasahe

### ISSUE THREAD

**Issue by Kasahe** [revoltchat/translations#145]
### What language(s) did you translate?

Armenians

### What is your Revolt ID?

01GNPRBTDX6QCJ31RNDCZKFQNJ

### Link to Weblate profile

https://weblate.insrt.uk/user/Kasahe/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
Closing in favour of #146.
