### ISSUE TITLE
badge: Bengali for Aurka

### ISSUE THREAD

**Issue by aurkaxi** [revoltchat/translations#149]
### What language(s) did you translate?

Bengali

### What is your Revolt ID?

01GVJX9P8GMY6XZZKFC1QZDQKJ

### Link to Weblate profile

https://weblate.insrt.uk/user/Aurka/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @Cynycal2003

**Comment by Cynycal2003** [comment]
Thank you for the mention!

Unfortunately I dont see much contributions of this user in Bengali translations

**Comment by Rexogamer** [comment]
Most of their translations seem to be for Leet, an automatically generated language. Declining for now; if you contribute more to Bengali or any other non automated language, please open a new badge request. Thanks!
