### ISSUE TITLE
maintain: Leet

### ISSUE THREAD

**Issue by aurkaxi** [revoltchat/translations#150]
### What language do you want to maintain?

Leet

### Link to Weblate profile

https://weblate.insrt.uk/user/Aurka/#contributed

### Revolt ID

01GVJX9P8GMY6XZZKFC1QZDQKJ

**Comment by Rexogamer** [comment]
This language is automatically translated and should not be modified.

**Comment by aurkaxi** [comment]
yes but there are some Checks to be reviewed.

**Comment by Rexogamer** [comment]
Again, it's automatically translated and should not be modified - ignore them
