### ISSUE TITLE
badge: Filipino for Dynamity

### ISSUE THREAD

**Issue by ghost** [revoltchat/translations#151]
### What language(s) did you translate?

Filipino

### What is your Revolt ID?

01GVNPYZ5J0PXVXNQ9SHTD8P2Q

### Link to Weblate profile

https://weblate.insrt.uk/user/dynamity/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @I2rys

**Comment by Rexogamer** [comment]
Issue author deleted their GitHub account; closing.
