### ISSUE TITLE
badge: Filipino for searinminecraft

### ISSUE THREAD

**Issue by searinminecraft** [revoltchat/translations#152]
### What language(s) did you translate?

Filipino

### What is your Revolt ID?

01GVN2K5RY5HYKZDV2SFYD8PNV

### Link to Weblate profile

https://weblate.insrt.uk/user/searinminecraft/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @I2rys

**Comment by searinminecraft** [comment]
just to update: it has been 2 months... what happened to the maintainer of the language?

**Comment by I2rys** [comment]
> just to update: it has been 2 months... what happened to the maintainer of the language?

I've got really busy in school but I'm trying my best to maintain it.

**Comment by searinminecraft** [comment]
> > just to update: it has been 2 months... what happened to the maintainer of the language?
> 
> I've got really busy in school but I'm trying my best to maintain it.

ah okay, thanks for the update.

**Comment by Rexogamer** [comment]
Any news?

**Comment by I2rys** [comment]
> Any news?

I think I finished translating them all. Most English nouns does not have a translation for filipino.

**Comment by Rexogamer** [comment]
I see - I was more asking if you could check Sear's contributions and approve/deny the badge request, but yeah

**Comment by I2rys** [comment]
> I see - I was more asking if you could check Sear's contributions and approve/deny the badge request, but yeah

Oh, my bad. Yes, I can approve, she/he has contributed a lot specially in the **OwO** language area of the web application, and has completed 99% of that part including the AutoMod bot.

**Comment by I2rys** [comment]
> I see - I was more asking if you could check Sear's contributions and approve/deny the badge request, but yeah

Oh, my bad. Yes, I can approve, she/he has contributed a lot specially in the **OwO** language area of the web application, and has completed 99% of that part including the AutoMod bot.

**Comment by Rexogamer** [comment]
I was more focused on their Filipino translations; I'm assuming they're also good?

**Comment by I2rys** [comment]
> I was more focused on their Filipino translations; I'm assuming they're also good?

Yes they're also good and accurate I checked his/her translations.

**Comment by searinminecraft** [comment]
alright, so now i just have to wait for my translator badge to be given to me?

**Comment by Rexogamer** [comment]
I'll get to it soon ^^
