### ISSUE TITLE
maintain: Español (Latinoamérica)

### ISSUE THREAD

**Issue by 7Macros** [revoltchat/translations#153]
### What language do you want to maintain?

Español (Latinoamérica)

### Link to Weblate profile

https://weblate.insrt.uk/user/7Macros/

### Revolt ID

01GVKKKJXW7C5R8E5192FCJNJ3

**Comment by Rexogamer** [comment]
Your translation count seems pretty low 🤔

**Comment by Rexogamer** [comment]
Fixed in 6fd1006cc4e7811688c9b2f8313a4a833998f6fa
