### ISSUE TITLE
maintain: Español (América Latina)

### ISSUE THREAD

**Issue by SrWesly** [revoltchat/translations#154]
### What language do you want to maintain?

Español (América Latina)

### Link to Weblate profile

https://weblate.insrt.uk/user/Wesly/

### Revolt ID

01GVC39VKM9T14MSN04P7A9EER

**Comment by SrWesly** [comment]
There is a small typo in Language.ts
![image](https://user-images.githubusercontent.com/85891667/227583115-8b46082d-d717-4a1d-b664-88aa60943084.png)

**Comment by Rexogamer** [comment]
Oops! Thanks for pointing that out; will fix shortly

**Comment by SrWesly** [comment]
You're welcome :)

**Comment by Rexogamer** [comment]
Fixed in 6fd1006cc4e7811688c9b2f8313a4a833998f6fa
