### ISSUE TITLE
badge: Latin for Rymko

### ISSUE THREAD

**Issue by rymko** [revoltchat/translations#158]
### What language(s) did you translate?

Latin

### What is your Revolt ID?

01GVT7QG1VMXK9C4NQZE9THHWX

### Link to Weblate profile

https://weblate.insrt.uk/user/Rymko/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by rymko** [comment]
Good evening, I have translated all the Latin and I would like to know if it is possible to have the badge. Thanks to you

**Comment by rymko** [comment]
good evening, is there a maintainer for the Latin?

**Comment by rymko** [comment]
Will I get an answer? @Rexogamer

**Comment by Rexogamer** [comment]
Closing in favour of #161
