### ISSUE TITLE
maintain: Turkish

### ISSUE THREAD

**Issue by ramazaneris** [revoltchat/translations#159]
### What language do you want to maintain?

Turkish

### Link to Weblate profile

https://weblate.insrt.uk/user/Jeosty/

### Revolt ID

01FCXFBQPYCBZWX40NSBYXYAWW

**Comment by Rexogamer** [comment]
cc @KerizAlperwastaken

**Comment by kerizalperwastaken** [comment]
@Rexogamer sorry for ping.

**Comment by Rexogamer** [comment]
Done in 99a1c5e63719cf6596b7cb45b069fc8663856a4c.
