### ISSUE TITLE
badge: POLISH for MAFINEEEK 

### ISSUE THREAD

**Issue by mafineeek** [revoltchat/translations#162]
### What language(s) did you translate?

Polish

### What is your Revolt ID?

01F9H4BS21C0NSJ2FEF6WV8F27

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by mafineeek** [comment]
* I had this badge for long months, today saw It's gone

**Comment by Rexogamer** [comment]
cc @jacekpoz

**Comment by jacekpoz** [comment]
sorry for the long wait, I was asleep

you haven't done anything in a long time I don't see why you'd want it back

**Comment by Rexogamer** [comment]
Rejected for now - feel free to re-apply if you make more contributions in the future. Thanks!
