### ISSUE TITLE
badge: Spanish for MDC

### ISSUE THREAD

**Issue by MDCYT** [revoltchat/translations#166]
### What language(s) did you translate?

Spanish

### What is your Revolt ID?

01GY0HEQ93GAPNZN1F3FKQ8YPM

### Link to Weblate profile

https://weblate.insrt.uk/user/MDC/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @fernandopal

**Comment by fernandopal** [comment]
Unfortunately I don't see too much contributions from this user to the Spanish language, I would reject it for now
