### ISSUE TITLE
badge: italian for Gabriele

### ISSUE THREAD

**Issue by Gabriele73** [revoltchat/translations#176]
### What language(s) did you translate?

Italian

### What is your Revolt ID?

01GZJSWWFGXKRCCB35QVQA6XCX

### Link to Weblate profile

https://weblate.insrt.uk/user/Gabriele/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @SingleSlice

**Comment by Gabriele73** [comment]
would have loved to contribute more but all the other lines were already finished lol

**Comment by Rexogamer** [comment]
That does seem pretty low so I'm somewhat tempted to decline but if they're of good quality I certainly wouldn't be opposed to accepting this when you've done more; the circumstances do seem understandable though, so hmmm

**Comment by Gabriele73** [comment]
no worries, I understand the sus circumstances lol. take your time for the right decision

**Comment by Gabriele73** [comment]
oh lol no worried, it's actually a nice thing you guys are putting effort into keeping it a gender neutral platform

**Comment by SingleSlice** [comment]
Tho, thinking about it, if you do think that you will keep on doing translations in the future, i wouldn't be against giving you the badge

**Comment by Gabriele73** [comment]
Yep, I for sure will do my best to keep on translating the platform being careful on keeping the gender neutral vibe going on. Thanks for the reply btw!

**Comment by Gabriele73** [comment]
Is it normal that the insrt.uk platform doesnt work as of now?

**Comment by Rexogamer** [comment]
Yes - we're currently doing some maintenance

**Comment by SingleSlice** [comment]
I now vote positive on the badge for @Gabriele73

**Comment by Gabriele73** [comment]
Thanks, I'll still be there to look around for more translations to do or improve current ones.

**Comment by Rexogamer** [comment]
Done in 99a1c5e63719cf6596b7cb45b069fc8663856a4c.
