### ISSUE TITLE
badge: Dutch for edenbee

### ISSUE THREAD

**Issue by edenbee** [revoltchat/translations#186]
### What language(s) did you translate?

Dutch

### What is your Revolt ID?

01H0NFRJD4DGWG44PKPWGFSACE

### Link to Weblate profile

https://weblate.insrt.uk/user/edenbee/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @sympact06

**Comment by sympact06** [comment]
Sorry but I don't think your contributions are helpful enough. Besides that the Dutch translation was already done and your improvements are not correctly written.
