### ISSUE TITLE
badge: Assamese for The Conner

### ISSUE THREAD

**Issue by TheActualConner** [revoltchat/translations#198]
### What language(s) did you translate?

Assamese

### What is your Revolt ID?

01H0T8FZM0MZWJM5J42KZXKKZ6 - @ The Conner™ # 0001

### Link to Weblate profile

https://weblate.insrt.uk/user/TheConner/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by TheActualConner** [comment]
The language does not have a maintainer, I have put in a request to maintain this language.

- https://github.com/revoltchat/translations/issues/197

**Comment by Rexogamer** [comment]
Closing in favour of #197.
