### ISSUE TITLE
badge: <language> for <your name>

### ISSUE THREAD

**Issue by DantumFlandrox** [revoltchat/translations#201]
### What language(s) did you translate?

Ukrain, Russian

### What is your Revolt ID?

01H14VRHCR9KBBWCWHW6MN2WE3

### Validations

- [x] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
Duplicate of #200.
