### ISSUE TITLE
maintain: <French>

### ISSUE THREAD

**Issue by Kasahe** [revoltchat/translations#205]
### What language do you want to maintain?

French

### Link to Weblate profile

https://weblate.insrt.uk/user/Kasahe/

### Revolt ID

01GNPRBTDX6QCJ31RNDCZKFQNJ

**Comment by Rexogamer** [comment]
cc @Hades785

**Comment by Hades785** [comment]
@Rexogamer approved.

**Comment by Kasahe** [comment]
Thank you, I'll do my best for the French translation of Revolt, it's a pleasure because it's my nationality. 🇫🇷🔥

**Comment by Rexogamer** [comment]
Done in 99a1c5e63719cf6596b7cb45b069fc8663856a4c.
