### ISSUE TITLE
badge: Latitn for Rymko

### ISSUE THREAD

**Issue by rymko** [revoltchat/translations#206]
### What language(s) did you translate?

Latin

### What is your Revolt ID?

184742

### Link to Weblate profile

https://weblate.insrt.uk/user/Rymko/

### Validations

- [ ] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Kasahe** [comment]
👍

**Comment by Rexogamer** [comment]
Closing in favour of #207.
