### ISSUE TITLE
badge: Portuguese (Brazil) for kyli0x

### ISSUE THREAD

**Issue by kyli0x** [revoltchat/translations#212]
### What language(s) did you translate?

Brazilian Portuguese

### What is your Revolt ID?

01G9KZT2WVRSH0ZDRNX5ASKKRN

### Link to Weblate profile

https://weblate.insrt.uk/user/kyli0x/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @yanndere

**Comment by kyli0x** [comment]
i did over 100 translations, tf

**Comment by kyli0x** [comment]
@Rexogamer  thats a bit janky, i do not give concent to use my translations that you already added to weblate, i did over 75% of the android translations that i request you remove, thank you

**Comment by Rexogamer** [comment]
I cannot remove your translations because your badge was declined.

**Comment by kyli0x** [comment]
> I cannot remove your translations because your badge was declined.

@Rexogamer exactly my point, you decline my badge but pushed my translations through. So you need to remove all my translations and have someone else do them. I do not give you permission to use my work

**Comment by kyli0x** [comment]
> I cannot remove your translations because your badge was declined.

@Rexogamer if my translations are not removed within 24 hours, I request your legal team contact, so I can settle this the correct way

**Comment by Rexogamer** [comment]
I cannot remove your translations. Further threats will lead to your ability to comment here being revoked.

**Comment by janderedev** [comment]
@kyli0x You have licensed your translations for the [Web App project](https://weblate.insrt.uk/projects/revolt/web-app/#information) to us under the Mozilla Public License 2.0, and to contribute to the Android project you signed a [license agreement](https://weblate.insrt.uk/contributor-agreement/revolt/android/?next=/projects/revolt/android/) which gives us ownership over your translations. You cannot revoke either of these.

Throwing a tantrum on GitHub won't bring you closer to getting a badge. Have fun reflecting on this clown behaviour a couple years down the road :)
