### ISSUE TITLE
maintain: Spanish for Gátomo

### ISSUE THREAD

**Issue by gatomod** [revoltchat/translations#213]
### What language do you want to maintain?
Spanish, Spanish (Latin America)

### Link to Weblate profile

https://weblate.insrt.uk/user/gatomo/

### Revolt ID

01G6V6HRE9DRG4H6RWVSNK128A

**Comment by Rexogamer** [comment]
cc @fernandopal

**Comment by fernandopal** [comment]
Approved

**Comment by gatomod** [comment]
Thanks. @fernandopal I have a little question. I'd be eligible as language maintainer or there are some requirements that I don't meet? I don't find any kind of information about that.

**Comment by fernandopal** [comment]
> Thanks. @fernandopal I have a little question. I'd be eligible as language maintainer or there are some requirements that I don't meet? I don't find any kind of information about that.

I don't think that is on my side to take that decision, probably It's more a thing of @Rexogamer

Just as an aside note, the other maintainer for spanish has been inactive for months so s little help wouldn't be bad as I'm very bussy lately with my work.

**Comment by gatomod** [comment]
> Just as an aside note, the other maintainer for spanish has been inactive for months so s little help wouldn't be bad as I'm very bussy lately with my work.
True. Well, it's nice to know that I'm able to help with that. I'm going to talk about maintaining the language with @Rexogamer.

**Comment by Rexogamer** [comment]
Apologies for the delayed response/wait but just to triple check I'll also ping @SrWesly for LatAm Spanish

**Comment by SrWesly** [comment]
Approved.

**Comment by Rexogamer** [comment]
Done in d385505598bd755a073c38fd8f4d2131bd15ac40.
