### ISSUE TITLE
badge: French for Gaby5873

### ISSUE THREAD

**Issue by Gaby5873** [revoltchat/translations#218]
### What language(s) did you translate?

French

### What is your Revolt ID?

01H2PRHQ7YXGKSD10ZBS95HPZV

### Link to Weblate profile

https://weblate.insrt.uk/user/Gaby5873/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Hades785** [comment]
Approved, already talked over on Revolt and overall pretty good quality.
Letting @Kasahe react if they want.

> What is your Revolt ID?
> Gaby#1736~~6~~

Got your actual ID here: `01H2PRHQ7YXGKSD10ZBS95HPZV`

**Comment by Hades785** [comment]
@Rexogamer just stumbled back on this (was a while ago and I noticed they never got their badge nor translator role on the server)

**Comment by Rexogamer** [comment]
Missed this one entirely - thanks for the reminder
