### ISSUE TITLE
badge: EN/PT for Awesoming

### ISSUE THREAD

**Issue by Aweesoming** [revoltchat/translations#220]
### What language(s) did you translate?

Inglês

### What is your Revolt ID?

01H2RDE0AZBRN7CRSNWX3TNRJN

### Link to Weblate profile

https://weblate.insrt.uk/user/Awesoming/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
You only have 4 translations - as such, I'll decline this one for now. If you make more contributions, please feel free to open a new request ^^
