### ISSUE TITLE
badge: Hindi for Experience#1674

### ISSUE THREAD

**Issue by anubhavhirani** [revoltchat/translations#223]
### What language(s) did you translate?

Hindi

### What is your Revolt ID?

01GZP0FV4EDJSD2B49TZXQYA6E

### Link to Weblate profile

https://weblate.insrt.uk/user/experience/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @Infiniticity

**Comment by Infiniticity** [comment]
You have not made enough translations, so I cannot accept your request. Feel free to apply again once you have!
