### ISSUE TITLE
badge: Spanish (Latin America) for Teriko

### ISSUE THREAD

**Issue by exelenuwu** [revoltchat/translations#227]
### What language(s) did you translate?

Spanish (Latin America)

### What is your Revolt ID?

01GGWJQNP0A52210PY59VCB1PV

### Link to Weblate profile

https://weblate.insrt.uk/user/Teriko/

### Validations

- [x] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by SrWesly** [comment]
I have seen good translations from this user. I approve this
