### ISSUE TITLE
maintain: Spanish

### ISSUE THREAD

**Issue by PanIntegralus** [revoltchat/translations#228]
### What language do you want to maintain?

Spanish

### Link to Weblate profile

https://weblate.insrt.uk/user/PanIntegral/

### Revolt ID

01FE88ZY56Y62J7896SC5308D4

**Comment by PanIntegralus** [comment]
I'm so sorry for opening this issue with the wrong information. I fixed it just now.

**Comment by Rexogamer** [comment]
cc @fernandopal

**Comment by fernandopal** [comment]
Please make more contributions before requesting the badge, your weblate profile shows only 4 contributions to spanish.
