### ISSUE TITLE
badge: ru_RU for TendingStream73

### ISSUE THREAD

**Issue by SachaTending** [revoltchat/translations#229]
### What language(s) did you translate?

Russian

### What is your Revolt ID?

01H2VCQ7FT2NEWFK4XSPY0T7T6

### Link to Weblate profile

https://weblate.insrt.uk/user/TendingStream73/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @div2005

**Comment by div2005** [comment]
As I see, there's is only one real translation and it's in Glossary. So, at this moment I can't approve your request. Come back with new contributions 😉
