### ISSUE TITLE
badge: <indonesian> for <Lieba Natur Brilian>

### ISSUE THREAD

**Issue by naturbrilian** [revoltchat/translations#232]
### What language(s) did you translate?

Indonesian (ID)

### What is your Revolt ID?

naturbrilian#8065

### Link to Weblate profile

https://weblate.insrt.uk/user/naturbrilian/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @liimee

**Comment by liimee** [comment]
I couldn't find any contributions...?

https://translate.revolt.chat/user/naturbrilian/contributions/

**Comment by Rexogamer** [comment]
Rejecting for now - feel free to re-apply if you make some contributions. Thanks!

**Comment by naturbrilian** [comment]
Okay
