### ISSUE TITLE
badge: Greek for G4b1tz#9407

### ISSUE THREAD

**Issue by tabakisp** [revoltchat/translations#233]
### What language(s) did you translate?

Greek

### What is your Revolt ID?

01H2WEVXCVT3M1ZKSJMG5P4V6F

### Link to Weblate profile

https://weblate.insrt.uk/user/g4b1tz/

### Validations

- [ ] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @SudoJanast

**Comment by tabakisp** [comment]
Just updated the issue, there is no current maintainer for Greek. I just finished translating and proofreading the whole webapp from scratch, if you need a maintainer for Greek, let me know. 

_PS. I would finish the Android repo too but it's locked._

**Comment by Rexogamer** [comment]
Closing in favour of maintainer request.
