### ISSUE TITLE
badge: Ukrainian and Russian for yui

### ISSUE THREAD

**Issue by zptr1** [revoltchat/translations#235]
### What language(s) did you translate?

Ukrainian, Russian

### What is your Revolt ID?

01FEPAFEEMVTP9MF7ZPBHBBZJY

### Link to Weblate profile

https://weblate.insrt.uk/user/yui/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @div2005

**Comment by div2005** [comment]
@Rexogamer approved

**Comment by Rexogamer** [comment]
Done in 82f0b19cd36ec0b782698416d9948348637893e6.
