### ISSUE TITLE
maintain: <language>

### ISSUE THREAD

**Issue by veteranoinsc** [revoltchat/translations#238]
### What language do you want to maintain?

Spanish

### Link to Weblate profile

https://weblate.insrt.uk/user/Poundscoin/

### Revolt ID

01H308N4V0V9YF2JY3898V2Q57

**Comment by Rexogamer** [comment]
You have not made any contributions - if you are asking for translator access, please make this clear

**Comment by veteranoinsc** [comment]
Yeah I'm asking for translation access, apologies.

**Comment by Rexogamer** [comment]
You should now have access - apologies for this by the way!
