### ISSUE TITLE
maintain: Danish

### ISSUE THREAD

**Issue by ZihengWisdom** [revoltchat/translations#239]
### What language do you want to maintain?

Danish

### Link to Weblate profile

https://weblate.insrt.uk/user/Ziheng/

### Revolt ID

01GHSF20SCZ0ZXBJ61JR45VFV2

**Comment by Rexogamer** [comment]
Assuming you're asking for translation access - if so, done

**Comment by ZihengWisdom** [comment]
Danish does not yet have a maintainer - would it be possible for me to apply for this position?
