### ISSUE TITLE
[TEMPORARY] Please put translation access requests here

### ISSUE THREAD

**Issue by Rexogamer** [revoltchat/translations#240]
Hey everyone! The TL;DR for the current situation is that I accidentally set the Revolt project to Restricted, but due to a Weblate bug (WeblateOrg/weblate#9416) I can't seem to set it back to Public. As such, for the moment you'll *have to ask for the ability to translate strings here*. 

Please **reply to this issue with a link to your Weblate profile** and I'll give you access. Again, this is a **temporary issue** - as soon as this is fixed, everyone will be able to translate strings as normal. Apologies!

**Comment by Cynycal2003** [comment]
Can you please give me access in Weblate? Thank you

My weblate profile → https://weblate.insrt.uk/user/Cynycal2003/

**Comment by searinminecraft** [comment]
still cant believe a weblate bug caused this issue

anyway:
https://weblate.insrt.uk/user/searinminecraft

**Comment by Achlys12** [comment]
Can you please give me access in Weblate? Thank you

My weblate profile → https://weblate.insrt.uk/user/Achlys/

**Comment by Rexogamer** [comment]
The upstream issue was [fixed](https://github.com/WeblateOrg/weblate/commit/428f7114be3bc79be61bd9fc26cd0472de3c68fb) in Weblate 4.18 - as such, you should now be able to translate as normal. Our apologies for this situation, but enjoy dark mode :3

**Comment by ZihengWisdom** [comment]
Hello I'd love to help with the Danish translations:
https://weblate.insrt.uk/user/Ziheng/
