### ISSUE TITLE
badge: Francais for Aylan#2305

### ISSUE THREAD

**Issue by Aylaaann** [revoltchat/translations#243]
### What language(s) did you translate?

Anglais > Flamand occidental / Anglais > Francais

### What is your Revolt ID?

01H34QWGR6C6A3JVVXA3HGH05E

### Link to Weblate profile

https://weblate.insrt.uk/user/Aylan/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
You have been blocked from Weblate for a week for repeatedly disruptive translations (including copying unmodified and incorrect translations and using machine translations). **Please stop.**
