### ISSUE TITLE
badge: Portuguese (Brazil) for Hokiper

### ISSUE THREAD

**Issue by Hokiper** [revoltchat/translations#245]
### What language(s) did you translate?

Brazilian Portuguese

### What is your Revolt ID?

01H2RK8KT6SVNQTJF8YFS3QP21

### Link to Weblate profile

https://weblate.insrt.uk/user/Hokiper/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
Done in 833494c06657bfb627ad6e96e313477e30f72d6d.
