### ISSUE TITLE
maintain: Czech

### ISSUE THREAD

**Issue by Fjuro** [revoltchat/translations#254]
### What language do you want to maintain?

Czech

### Link to Weblate profile

https://translate.revolt.chat/user/Fjuro/

### Revolt ID

01FN8ZSVH7HRMKFJTV4J9DJ342

**Comment by Rexogamer** [comment]
Czeched a few of your translations and they appear to be fine ^^

**Comment by DeclanChidlow** [comment]
> Czeched a few of your translations and they appear to be fine ^^

I've got nothing to do with translations at Revolt but I saw this and had to give you thumbs up. That was a good one.

**Comment by Fjuro** [comment]
Nice one :smile: Thanks, is there anything I need to do? (except from translating of course)

**Comment by Rexogamer** [comment]
Not at the moment; I'll process this request at some point ^^

**Comment by Fjuro** [comment]
Okay, thank you!

**Comment by Fjuro** [comment]
Hey there, any news about this?

**Comment by Rexogamer** [comment]
This got lost in the shuffle, apologies - I'll run the script soon-ish :3

**Comment by Fjuro** [comment]
No problem, thanks!
