### ISSUE TITLE
badge:  pt_BR for KitsuShiro

### ISSUE THREAD

**Issue by YoshiroOno** [revoltchat/translations#263]
### What language(s) did you translate?

Brazilian Portuguese

### What is your Revolt ID?

01H84AH6MMVPJDQ8RGD6YE0SBE

### Link to Weblate profile

https://translate.revolt.chat/user/KitsuShiro/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @yanndere

**Comment by YoshiroOno** [comment]
he does not seem to be actively accessing github, only weblate.

**Comment by YoshiroOno** [comment]
sure, I'll keep an eye out for these details.

I considered the understandability of the users at the time I was translating, so at some point there was a mismatch, because I didn't check the string in which it was attached.
