### ISSUE TITLE
badge: French for Ayl3

### ISSUE THREAD

**Issue by Ay337** [revoltchat/translations#273]
### What language(s) did you translate?

French

### What is your Revolt ID?

01H34QWGR6C6A3JVVXA3HGH05E

### Link to Weblate profile

https://translate.revolt.chat/user/Ayl3/#changes

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Ay337** [comment]
Hello, I only translate French & I had a question why the translation “Revolt/android - French” is closed.

**Comment by TapwaveZodiac** [comment]
The Android app is being rebuilt and they froze the translation until it's ready.

**Comment by Ay337** [comment]
OK thank you for the information, who takes care of validation to have the role on the translator server ?

**Comment by ay700r** [comment]
@Rexogamer

**Comment by Rexogamer** [comment]
Someone needs to approve/deny this badge request before i can do anything, also, you're a different person..?

**Comment by ay700r** [comment]
sorry I think it was up to you to approve, I'll wait sorry again

**Comment by Rexogamer** [comment]
cc @TapwaveZodiac for approval

**Comment by TapwaveZodiac** [comment]
> cc @TapwaveZodiac for approval

Very few contributions, mostly touchups due to English string updates.

Some broke consistency with identical strings (the OK one, mostly), so I encourage you to check similar/identical strings first. Remember that accessibility & consistency is key.

There are many unfinished strings you can work on, I'll take a look at your contributions afterwards and I can vouch for a badge after you made a pass.

**Comment by ay700r** [comment]
@TapwaveZodiac It has no problem, thank you for your answer I would give my free time to give more contribution to this, thank you again

**Comment by ay700r** [comment]
@TapwaveZodiac Désolé pour la mention, que pensez-vous de ma contribution actuelle ? Une plus grande participation est-elle nécessaire ?

**Comment by ay700r** [comment]
someone there ?

**Comment by TapwaveZodiac** [comment]
Pretty sweeping prep work of the Android version. Looks mostly fine to me, so I'm approving. However, pay attention to:

• Vérification de l'orthographe (j'ai quelques lettres échangées)
• Les accords singuliers/pluriels (il faut bien vérifier le contexte de l'élément pour être sûr)

Generally those are small and easily fixed so I can just do a pass and it'll be fine.

**Comment by ay700r** [comment]
ok thank you very much, I will pay more attention thank you for your approval it really makes me happy, I will pay attention to all of this
