### ISSUE TITLE
badge:  french for Lùka Guyonvarch

### ISSUE THREAD

**Issue by opastudien** [revoltchat/translations#276]
### What language(s) did you translate?

French

### What is your Revolt ID?

01G59HTJBX6J6HN3GDR4600Y8Z

### Link to Weblate profile

https://translate.revolt.chat/user/ventistudio/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @Achlys12

**Comment by TapwaveZodiac** [comment]
Very few translations. Mostly keyboard inputs.
Can't make an appropriate judgment yet. Needs more contributions.

**Comment by Achlys12** [comment]
I think everything has already been said, and sorry for the delay in the
response


Le jeu. 2 nov. 2023 à 11:54, TapwaveZodiac ***@***.***> a
écrit :

**Comment by Rexogamer** [comment]
Declined for now - if you make more contributions in the future, feel free to re-apply. Thank you!

**Comment by opastudien** [comment]
I have made more contributions I would like to know if I should reapply or simply tell you here?
