### ISSUE TITLE
maintain: Ijeða

### ISSUE THREAD

**Issue by dublUayaychtee** [revoltchat/translations#277]
### What language do you want to maintain?

Ijeða (conlang)

### Link to Weblate profile

https://translate.revolt.chat/user/dublUayaychtee/

### Revolt ID

01FJZQN5FRKSANV8NBY32R2DSV

**Comment by Rexogamer** [comment]
You haven't made any translations?

**Comment by dublUayaychtee** [comment]
Hello, I wanted to make a language file for Ijeða conlang, which doesn't have a file to make any translations on it. I was told to make a issue here to get it added. If I should use a different method to load custom language file that would be good too. Sorry for the confusion

**Comment by Rexogamer** [comment]
Hmmm... the current conlangs we have are generally larger, so I'm not 100% sure about adding this one since the community seems pretty small?

**Comment by dublUayaychtee** [comment]
Ok, I wasn't sure. Do you know if there's another way to load language files? Maybe through the experimental plugins thing. Thank you for your help

**Comment by Rexogamer** [comment]
Unfortunately I'm not aware of any other methods to load languages :(

**Comment by dublUayaychtee** [comment]
That's alright, thank you for your time!
