### ISSUE TITLE
badge: Spanish for arxify

### ISSUE THREAD

**Issue by DevArxify** [revoltchat/translations#280]
### What language(s) did you translate?

Spanish

### What is your Revolt ID?

01FNS96STXZPRREQDW6Y7MTWZ7

### Link to Weblate profile

https://translate.revolt.chat/user/arxify/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by DevArxify** [comment]
@z3ro0k @fernandopal @gatomod revisad esto xfa jajajaj

**Comment by gatomod** [comment]
Hi @DevArxify. First of all is @Rexogamer who mentions us because she manages translations and badge assignments.
Anyway, strings looks nice, I don't see any errors. I'll check your strings later or tomorrow to see if there's something wrong.

Approved
