### ISSUE TITLE
badge: translator for junsred#2438

### ISSUE THREAD

**Issue by EIE-elpelon** [revoltchat/translations#305]
### What language(s) did you translate?

Spanish, Portuguese

### What is your Revolt ID?

01HJYJQJZVCTZVVHB6FG5GE692

### Link to Weblate profile

https://translate.revolt.chat/user/junsred

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @gatomod and @Tmpod

**Comment by gatomod** [comment]
I reviewed it and I think it's okay. There are a few errors but un general are good.

**Comment by Tmpod** [comment]
I hadn't yet look at this Portuguese translations.  
@EIE-elpelon your translations are okay, but should be done in the "Portuguese (Brazil)" (`pt_BR`) branch, not just "Portuguese" (`pt`), that is for European Portuguese. I will tweak and fix your contributions to fit the latter, and I ask you to replay those strings in the correct branch.  
Thank you!

**Comment by gatomod** [comment]
@Rexogamer can you check if everything is okay? The user told me that is still waiting for the badge approval

**Comment by Rexogamer** [comment]
I was waiting on Tmpod to approve or deny

**Comment by Tmpod** [comment]
Apologies, I completely forgot about this :(
I approve the badge.
