### ISSUE TITLE
resign: Polish

### ISSUE THREAD

**Issue by jacekpoz** [revoltchat/translations#310]
### What language do you want to maintain?

Polish

### Link to Weblate profile

https://translate.revolt.chat/user/jacekpoz/

### Revolt ID

01FZ3YGZS3GEYAMMBM2D07XV36

**Comment by jacekpoz** [comment]
no issue template for resigning so I used this one, please remove me as a maintainer

**Comment by Rexogamer** [comment]
I am personally curious as to why - although fair if you'd rather not say/want to do so privately - but fair enough; sorry to see you go, but thanks for your work :3

**Comment by jacekpoz** [comment]
haven't contributed in a while and kinda forgot about the platform so no point in staying

what reminded me about revolt is [this post](https://wetdry.world/@amycatgirl/112418743522495043) - I was aware about discover not being foss (and openly against it) but until seeing the post I had no idea the mobile apps are proprietary

taking that decision in the first place isn't something I'd expect from you, it isn't the revolt I joined or the direction I wanted it to go, infi's response feels rushed and pressured by someone noticing you're making proprietary clients - not something you (or Jennifer alone, not sure who works on what) actually wanted to do

anyhow, I still wish you luck with the project, just not a platform I want to use anymore due to these decisions

**Comment by Rexogamer** [comment]
Completely understandable - and to be clear, I am not involved with the development of any mobile app other than RVMob/personally oppose the closed source components being closed. Thanks again for what you've done :3
