### ISSUE TITLE
About "Early Adopter Badge" been removed.

### ISSUE THREAD

**Issue by ramazaneris** [revoltchat/translations#318]
I had early adopter badge. I have not been Revolt in a for long time. When I entered again, I saw that there was no badge.
**Is everything okey there?**
**Before** : 
<img src="https://github.com/revoltchat/translations/assets/71462879/aa007e59-ed8d-4b6c-84e5-5db954781bea" width="350"/>
**Now** : 
<img src="https://github.com/revoltchat/translations/assets/71462879/9232d32a-e23d-49e1-9e19-a5699ca52bec" width="350"/>

**Comment by Rexogamer** [comment]
please send an email to support@revolt.chat with your user ID. apologies for this!
