### ISSUE TITLE
badge: Latvian for GGLVXD

### ISSUE THREAD

**Issue by GGLVXD** [revoltchat/translations#339]
### What language(s) did you translate?

Latvian

### What is your Revolt ID?

01HYMXQTYXTZZKQAGFZ13PZKSW

### Link to Weblate profile

https://translate.revolt.chat/user/GGLVXD/

### Validations

- [x] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [x] You agree that your translations are to a reasonable standard.

**Comment by DeclanChidlow** [comment]
Badge applied and added as contributor.
1cb1cd29cda9aaca506a08f0512ccb9da1f00470
