### ISSUE TITLE
badge: <language> for <zee.html>

### ISSUE THREAD

**Issue by zee-html** [revoltchat/translations#343]
### What language(s) did you translate?

cebuano, filipino

### What is your Revolt ID?

zee.html#7655

### Link to Weblate profile

https://translate.revolt.chat/user/zee.html/

### Validations

- [x] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [x] You agree that your translations are to a reasonable standard.

**Comment by DeclanChidlow** [comment]
Done with 91d8fa0c146273309ba4474cbdba7ebfc87d8e0e
