### ISSUE TITLE
badge: <language> for <your name>

### ISSUE THREAD

**Issue by vesley1** [revoltchat/translations#345]
### What language(s) did you translate?

Turkish

### What is your Revolt ID?

01JAA77DD0MJSZ9KBNGETJVEV8

### Validations

- [x] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [x] You agree that your translations are to a reasonable standard.

**Comment by DeclanChidlow** [comment]
Duplicate of #346 346
