### ISSUE TITLE
badge: <Turkish> for <vesley>

### ISSUE THREAD

**Issue by vesley1** [revoltchat/translations#346]
### What language(s) did you translate?

Turkish

### What is your Revolt ID?

01JAA77DD0MJSZ9KBNGETJVEV8

### Link to Weblate profile

(https://translate.revolt.chat/user/vesley/)

### Validations

- [x] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [x] You agree that your translations are to a reasonable standard.

**Comment by DeclanChidlow** [comment]
Added as contributor and badge applied.
fec1006abbffd06cd453191fb74c095f3b6a8c1c
