### ISSUE TITLE
maintain: Portuguese (Brazil)

### ISSUE THREAD

**Issue by ghost** [revoltchat/translations#35]
### What language do you want to maintain?

Brazilian Portuguese

### Link to Weblate profile

https://weblate.insrt.uk/user/yann/

### Revolt ID

01F9C4HMAQWY1KBBBPHN6SZZSB

**Comment by insertish** [comment]
Hi, you now have access to review strings on Weblate.
I've changed the form to also include a request for Revolt ID, could you please provide this?
There's no obligation to but it's used as an additional communication channel and for badge management.
