### ISSUE TITLE
maintain: French

### ISSUE THREAD

**Issue by Hades785** [revoltchat/translations#37]
### What language do you want to maintain?

French [fr_FR]

### Link to Weblate profile

https://weblate.insrt.uk/user/Fuzuki/

### Revolt ID

01FCY1KBKX3ZE2PCMPSTGW2NPT

**Comment by insertish** [comment]
You have been listed as a maintainer for the given language and can now review strings on Weblate.
Commit: 3fd235f2e7e007c535ffae0906e55e72cccb6253
