### ISSUE TITLE
badge: Russian for u032

### ISSUE THREAD

**Issue by u032** [revoltchat/translations#40]
### What language(s) did you translate?

Russian

### What is your Revolt ID?

01G45CXWDPQ116GZ1RDQ2KES42

### Link to Weblate profile

https://weblate.insrt.uk/user/u032/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by insertish** [comment]
Closing since you've applied for maintainer for Estonian: https://github.com/revoltchat/translations/issues/46
