### ISSUE TITLE
maintain: Arabic

### ISSUE THREAD

**Issue by LedaThemis** [revoltchat/translations#41]
### What language do you want to maintain?

Arabic

### Link to Weblate profile

https://weblate.insrt.uk/user/Leda/

### Revolt ID

01G4PRN8ZGM8HF61TTVC7AZR2V

**Comment by insertish** [comment]
You have been listed as a maintainer for the given language and can now review strings on Weblate.
Commit: 3fd235f2e7e007c535ffae0906e55e72cccb6253
