### ISSUE TITLE
badge: <language> for <your name>

### ISSUE THREAD

**Issue by 1Azula** [revoltchat/translations#44]
### What language(s) did you translate?

Northern Kurdish

### What is your Revolt ID?

01G4E9WY3P3A76C49AY9W76FD7

### Link to Weblate profile

https://weblate.insrt.uk/user/Azula/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by insertish** [comment]
> - [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).

Northern Kurdish does not currently have a maintainer and as such there's no party to check this issue.
You can however become a maintainer which also grants the same badge.
