### ISSUE TITLE
maintain: Estonian Language

### ISSUE THREAD

**Issue by u032** [revoltchat/translations#46]
### What language do you want to maintain?

Estonian

### Link to Weblate profile

https://weblate.insrt.uk/user/u032/

### Revolt ID

01G45CXWDPQ116GZ1RDQ2KES42

**Comment by insertish** [comment]
You have been listed as a maintainer for the given language and can now review strings on Weblate.
Commit: 3fd235f2e7e007c535ffae0906e55e72cccb6253
