### ISSUE TITLE
maintain: Persian

### ISSUE THREAD

**Issue by DevEvil99** [revoltchat/translations#48]
### What language do you want to maintain?

Persian/Farsi

### Link to Weblate profile

https://weblate.insrt.uk/user/DevEvil/

### Revolt ID

01FKGCCMX3EK90GRNWM16T6YBH

**Comment by insertish** [comment]
You have been listed as a maintainer for the given language and can now review strings on Weblate.
Commit: 3fd235f2e7e007c535ffae0906e55e72cccb6253
