### ISSUE TITLE
maintain: owo speak

### ISSUE THREAD

**Issue by FanMclaine** [revoltchat/translations#49]
### What language do you want to maintain?

owo speak >~<

### Link to Weblate profile

https://weblate.insrt.uk/user/Mclnoot/

### Revolt ID

01FWXJEHNR87E0HXDMSMDZ7ZAW

**Comment by Rexogamer** [comment]
The OwO language is, as faw as I know, autogenewated

**Comment by insertish** [comment]
![Screenshot_20220606_193100](https://user-images.githubusercontent.com/38285861/173624065-02fbe48c-153b-4a41-a371-1ce25d241cda.png)

**Comment by insertish** [comment]
@Rexogamer @infi should we be allowing maintainers for non-foreign languages

**Comment by Rexogamer** [comment]
Personally, I think these should be maintained by one of us - bear in mind that OwO is the only non-automatically generated non-foreign language AFAIK

**Comment by FanMclaine** [comment]
> Personally, I think these should be maintained by one of us - bear in mind that OwO is the only non-automatically generated non-foreign language AFAIK

![image](https://user-images.githubusercontent.com/66262586/176428743-2b4bcaa0-46b8-4f1f-a1e7-951e65a3cb19.png)

**Comment by insertish** [comment]
I'm forcibly adding Jan as a maintainer too :trollface:

something something

You have been added as a maintainer, for next steps please read: https://github.com/revoltchat/translations#what-do-i-do
