### ISSUE TITLE
badge: Estonian for u032

### ISSUE THREAD

**Issue by orchst** [revoltchat/translations#50]
### What language(s) did you translate?

Estonian

### What is your Revolt ID?

01G45CXWDPQ116GZ1RDQ2KES42

### Link to Weblate profile

https://weblate.insrt.uk/user/u032/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by u032** [comment]
@insertish

**Comment by insertish** [comment]
Closed in #40
