### ISSUE TITLE
badge: Spanish for Atzu

### ISSUE THREAD

**Issue by z3ro0k** [revoltchat/translations#51]
### What language(s) did you translate?

Spanish

### What is your Revolt ID?

01G5MQBMP34AM3M7G9X0RY2BD6

### Link to Weblate profile

https://weblate.insrt.uk/user/Atzu/

### Validations

- [ ] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by u032** [comment]
Spanish has no maintainer

**Comment by z3ro0k** [comment]
> Spanish has no maintainer

yes i am

**Comment by Rexogamer** [comment]
u032 is right - it does not have a listed maintainer

**Comment by insertish** [comment]
Closed in #53
