### ISSUE TITLE
maintain: Spanish (Neutral)

### ISSUE THREAD

**Issue by fernandopal** [revoltchat/translations#55]
### What language do you want to maintain?

Spanish (Neutral)

### Link to Weblate profile

https://weblate.insrt.uk/user/fpalomo/

### Revolt ID

01G5WFNS87C1HXJSR62QGG2FCH

**Comment by insertish** [comment]
You have been added as a maintainer, for next steps please read: https://github.com/revoltchat/translations#what-do-i-do
