### ISSUE TITLE
maintain: Portuguese (Portugal)

### ISSUE THREAD

**Issue by Tmpod** [revoltchat/translations#56]
### What language do you want to maintain?

Portuguese (Portugal)

### Link to Weblate profile

https://weblate.insrt.uk/user/tmpod/

### Revolt ID

01FE8TASJB796NPMZGVTDNVXKK

**Comment by insertish** [comment]
You have been added as a maintainer, for next steps please read: https://github.com/revoltchat/translations#what-do-i-do

**Comment by Tmpod** [comment]
Thank you!
