### ISSUE TITLE
maintain: Arabic

### ISSUE THREAD

**Issue by bIur04** [revoltchat/translations#60]
### What language do you want to maintain?

Arabic

### Link to Weblate profile

https://hosted.weblate.org/user/Blurem/

### Revolt ID

01G7X5BWDH0CH2GDM8KG0MFWQ4

NOTE: I'm aware that there's another member already maintaining the language however I'd like to further assist as the Arabic language has many dialects.

**Comment by insertish** [comment]
Translations are done on our own Weblate instance (https://weblate.insrt.uk/). I'm not entirely sure what you were editing if I'm understanding this correctly?

If you're still interested in maintaining the translation please re-open with a link to a profile on our instance.
