### ISSUE TITLE
maintain: <language>

### ISSUE THREAD

**Issue by Joelkka** [revoltchat/translations#61]
### What language do you want to maintain?

Spanish/Español, Portugués/Portuguese (português)

### Link to Weblate profile

https://weblate.insrt.uk/user/JoulXD/

### Revolt ID

01G86Q2271J9J3TW0WZS1E1K0Z

**Comment by insertish** [comment]
We currently have two maintainers listed for both Spanish and Portuguese, can I just double-check that you're still wanting to join up as a maintainer? I don't know if you're still active or not looking at the profile.

(please re-open if interested)
