### ISSUE TITLE
maintain: Catalan, Modern

### ISSUE THREAD

**Issue by TallerThanShort** [revoltchat/translations#62]
### What language do you want to maintain?

Catalan, Modern

### Link to Weblate profile

https://weblate.insrt.uk/user/TallerThanShort/

### Revolt ID

01FQ462YNBSWGV0K5DWTRZNJYQ

**Comment by TallerThanShort** [comment]
I could also do Catalan, Traditional.
Other va riations of Spanish aren't to my knowledge, but living in the Catalan region I know enough Catalan to be able to understand both versions of Catalan.

Should I make a new issue to add a language for Traditional Catalan?

**Comment by insertish** [comment]
You have been added as a maintainer, for next steps please read: https://github.com/revoltchat/translations#what-do-i-do

P.S. You can create a separate issue.
