### ISSUE TITLE
badge(pending): German for nitrobw

### ISSUE THREAD

**Issue by nitrobw** [revoltchat/translations#64]
### What language(s) did you translate?

German

### What is your Revolt ID?

01FJ83MABH61025M5Y7YA7FF6V

### Link to Weblate profile

https://weblate.insrt.uk/user/nitrobw/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by insertish** [comment]
@janderedev @infi could I have one of you [check over contributions](https://weblate.insrt.uk/changes/?user=nitrobw&project=&lang=de&user=nitrobw&start_date=&end_date=)?

**Comment by janderedev** [comment]
Woops, I thought I replied here but apparently I forgot - The translations look fine to me though, thanks for your help <3

**Comment by Rexogamer** [comment]
Done in a9033147a3ee2fb5ecf3ace484ac6b3f7eb4b01b; thanks for your contributions ^^
