### ISSUE TITLE
maintain Language Norwegian (Norsk Bokmål)

### ISSUE THREAD

**Issue by tobggs** [revoltchat/translations#66]
### What language do you want to maintain?

Norwegian (Norsk Bokmål)

### Link to Weblate profile

https://weblate.insrt.uk/user/tobggs/

### Revolt ID

01FDA6WQKMW3EH4N9RY6AGA37N

**Comment by insertish** [comment]
You have been added as a maintainer, for next steps please read: https://github.com/revoltchat/translations#what-do-i-do
