### ISSUE TITLE
maintain: Chinese (Traditional)

### ISSUE THREAD

**Issue by Zhuzi-ouo** [revoltchat/translations#69]
### What language do you want to maintain?

Chinese Traditional

### Link to Weblate profile

https://weblate.insrt.uk/user/Zhuzi/

### Revolt ID

01FFHWGZXWV6H6S3TAVRDHGA7X

**Comment by insertish** [comment]
You have been added as a maintainer, for next steps please read: https://github.com/revoltchat/translations#what-do-i-do
