### ISSUE TITLE
maintain: Lithuanian

### ISSUE THREAD

**Issue by ErnestasKaralius** [revoltchat/translations#70]
### What language do you want to maintain?

Lithuanian

### Link to Weblate profile

https://weblate.insrt.uk/user/KingErnest/

### Revolt ID

01GAWW0T29WD5BEHF6NN6B4VNG

**Comment by insertish** [comment]
You have been added as a maintainer, for next steps please read: https://github.com/revoltchat/translations#what-do-i-do
