### ISSUE TITLE
Maintain Slovak Language

### ISSUE THREAD

**Issue by ShadowLp174** [revoltchat/translations#74]
### What language do you want to maintain?

Slovak 

### Link to Weblate profile

https://weblate.insrt.uk/user/ShadowLp174/

### Revolt ID

01G9MCW5KZFKT2CRAD3G3B9JN5

**Comment by insertish** [comment]
You have been added as a maintainer, for next steps please read: https://github.com/revoltchat/translations#what-do-i-do
