### ISSUE TITLE
maintain: Turkish 

### ISSUE THREAD

**Issue by KerizAlperwastaken** [revoltchat/translations#75]
### What language do you want to maintain?

Turkish

### Link to Weblate profile

https://weblate.insrt.uk/user/kerizalper/

### Revolt ID

01FWY6ZGDB08N8D8B2N5B4DCM8

**Comment by insertish** [comment]
You have been added as a maintainer, for next steps please read: https://github.com/revoltchat/translations#what-do-i-do
