### ISSUE TITLE
badge: <language> for <your name>

### ISSUE THREAD

**Issue by S703T** [revoltchat/translations#76]
### What language(s) did you translate?

Romanian

### What is your Revolt ID?

01GC479933RX4JWDAYQN63K9FH

### Link to Weblate profile

https://weblate.insrt.uk/user/Secsi/

### Validations

- [ ] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by insertish** [comment]
Granting on the basis no maintainer is available to verify translations.
