### ISSUE TITLE
maintain: <language>

### ISSUE THREAD

**Issue by weasles** [revoltchat/translations#78]
### What language do you want to maintain?

Japanese

### Link to Weblate profile

https://weblate.insrt.uk/user/chelley/

### Revolt ID

01FM3AEE16Z5T7ZVCECF7XT7CQ

**Comment by insertish** [comment]
You have been added as a maintainer, for next steps please read: https://github.com/revoltchat/translations#what-do-i-do

**Comment by chelIey** [comment]
by the way I changed my username for parity reasons so the name on the table might not work anymore. it's @chelIey now
