### ISSUE TITLE
badge(pending): Swedish for YouTubeGameNana

### ISSUE THREAD

**Issue by YouTubeGameNana** [revoltchat/translations#81]
### What language(s) did you translate?

Swedish

### What is your Revolt ID?

01GCADPN83KY273XFWXG2NVM4N

### Link to Weblate profile

https://weblate.insrt.uk/user/seven/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by insertish** [comment]
cc @raggebatman could you check over [quality of changes](https://weblate.insrt.uk/changes/?page=1&limit=20&lang=sv&user=seven)?

**Comment by raggebatman** [comment]
Thought to comment on this one as well so we can close it @Rexogamer
These are most definitely machine translated as there are a couple hiccups scattered around. Would not consider them for the badge even if I was on time lol.
