### ISSUE TITLE
badge: Turkish for KerizAlper

### ISSUE THREAD

**Issue by kerizalperwastaken** [revoltchat/translations#88]
### What language(s) did you translate?

Turkish

### What is your Revolt ID?

01FWY6ZGDB08N8D8B2N5B4DCM8

### Link to Weblate profile

https://weblate.insrt.uk/user/kerizalper/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @KerizAlperwastaken

**Comment by Rexogamer** [comment]
Just realised this is now irrelevant as you latterly became a maintainer for Turkish; closing as a duplicate issue
