### ISSUE TITLE
badge: <sinhala> for <helabasa>

### ISSUE THREAD

**Issue by hanariyada** [revoltchat/translations#90]
### What language(s) did you translate?

sinhala

### What is your Revolt ID?

01GF7918C8Z5PZ0NAFRTPN4VKH

### Link to Weblate profile

https://weblate.insrt.uk/user/helabasa/

### Validations

- [ ] The language has a maintainer, see https://github.com/revoltchat/translations/issues/91#issuecomment-1276871396
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
Closing in favour of #91.
