### ISSUE TITLE
badge: Polish for CyberL1

### ISSUE THREAD

**Issue by CyberL1** [revoltchat/translations#94]
### What language(s) did you translate?

Polish

### What is your Revolt ID?

01GJ3RDVQSZZ0MMDD06Q6CK72E

### Link to Weblate profile

https://weblate.insrt.uk/user/CyberL1/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @jacekpoz

**Comment by jacekpoz** [comment]
are you asking me if they guy should be given the badge? he didn't do a lot, but his translations are pretty good

**Comment by Rexogamer** [comment]
I was; good to hear ^^

**Comment by jacekpoz** [comment]
where's my badge btw

**Comment by jacekpoz** [comment]
nvm I have it

**Comment by Rexogamer** [comment]
Done in 8ecd1a1
