### ISSUE TITLE
maintain: Thailand

### ISSUE THREAD

**Issue by xhayper** [revoltchat/translations#96]
### What language do you want to maintain?

Thailand

### Link to Weblate profile

https://weblate.insrt.uk/user/hayper/

### Revolt ID

01GHBV31SY9JFNZ7W8TRRXWEWZ

**Comment by Rexogamer** [comment]
Looks good to me; will grant maintainer perms in a bit

**Comment by Rexogamer** [comment]
Done in 8ecd1a1
