### ISSUE TITLE
maintain: Simplified Chinese (zh_Hans)

### ISSUE THREAD

**Issue by deluxghost** [revoltchat/translations#97]
### What language do you want to maintain?

Simplified Chinese (zh_Hans)

### Link to Weblate profile

https://weblate.insrt.uk/user/deluxghost/

### Revolt ID

01FD6H5SC7Y4T09W6HDK36Y275

**Comment by Rexogamer** [comment]
Simplified Chinese doesn't seem to have a maintainer

**Comment by deluxghost** [comment]
> Simplified Chinese doesn't seem to have a maintainer

Guess what is this issue for

**Comment by Rexogamer** [comment]
I mistook this for a badge request; no need to be rude

**Comment by Rexogamer** [comment]
In any case, looks fine to me

**Comment by deluxghost** [comment]
> I mistook this for a badge request; no need to be rude

Sorry, my bad

**Comment by Rexogamer** [comment]
Done in 8ecd1a1
