### ISSUE TITLE
badge: Hindi for CodeWhiteOfficial

### ISSUE THREAD

**Issue by CodeWhiteWeb** [revoltchat/translations#98]
### What language(s) did you translate?

Hindi

### What is your Revolt ID?

01G4C4PGY00H64WTXJRX7V64H0

### Link to Weblate profile

https://weblate.insrt.uk/user/CodeWhite

### Validations

- [X] You agree that your translations are to a reasonable standard.
- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).

**Comment by Rexogamer** [comment]
cc @Infiniticity

**Comment by Infiniticity** [comment]
Approved.

**Comment by Rexogamer** [comment]
Done in 4f325d2
