### ISSUE TITLE
badge: Irish for Codeize

### ISSUE THREAD

**Issue by Codeize** [revoltchat/translations#99]
### What language(s) did you translate?

Irish

### What is your Revolt ID?

01FEZEKT1T7YN9708A6MJ8088C

### Link to Weblate profile

https://weblate.insrt.uk/user/Codeize/

### Validations

- [ ] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
This one's tough - Irish doesn't currently have a maintainer, but your changes mostly appear to be capitalisation/wording tweaks, and a friend who speaks some Irish has said your changes look fine, so hmmm

**Comment by Rexogamer** [comment]
Apologies for the lack of response - in future, I'll find an Irish maintainer

**Comment by Codeize** [comment]
> Apologies for the lack of follow-up - in future, I'll find an Irish maintainer 

You're all good, I wouldn't have time now to contribute so it isn't fair that I have a badge for translations if I'm not going to contribute. Thanks.
